# Generated by Django 4.0.3 on 2023-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sectionselection_message_sectionselection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.IntegerField()),
                ('mentor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
