# Generated by Django 4.0.4 on 2023-03-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_id_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedcourse',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', unique=True),
        ),
    ]
